# Generated by Django 3.0.7 on 2020-07-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicd4ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('state', models.CharField(choices=[('ALIVE', 'Alive'), ('DEAD', 'Dead')], max_length=10)),
                ('connected_at', models.DateTimeField()),
                ('last_heart_beat', models.DateTimeField()),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicd4ml.Runner')),
            ],
        ),
    ]
