# Generated by Django 3.0.7 on 2020-07-25 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicd4ml', '0002_registeredrunner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=200)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicd4ml.Runner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicd4ml.Project')),
            ],
        ),
    ]
