# Generated by Django 3.1.1 on 2020-10-08 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicd4ml', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assigned_runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cicd4ml.registeredrunner'),
        ),
    ]
